services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-caseuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-casepass}
      POSTGRES_DB: ${DB_NAME:-backend_case}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      ENV: dev
      SECRET_KEY: ${SECRET_KEY:-devsecret}
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      DB_USER: ${DB_USER:-caseuser}
      DB_PASSWORD: ${DB_PASSWORD:-casepass}
      DB_NAME: ${DB_NAME:-backend_case}
      DB_HOST: db
      DB_PORT: 5432
      DATABASE_URL: postgresql+psycopg://${DB_USER:-caseuser}:${DB_PASSWORD:-casepass}@db:5432/${DB_NAME:-backend_case}
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app

volumes:
  dbdata:
